- name: Installation d'OpenSSH Server et Google Authenticator
  ansible.builtin.apt:
    name:
      - openssh-server
      - libpam-google-authenticator
    state: present
    update_cache: yes
  become: yes

- name: Déploiement de la configuration SSH
  ansible.builtin.template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: '0644'
  notify: Restart SSH
  become: yes

- name: Vérification que pam_google_authenticator est dans la config PAM
  ansible.builtin.lineinfile:
    path: /etc/pam.d/sshd
    regexp: '^auth required pam_google_authenticator.so'
    line: 'auth required pam_google_authenticator.so'
    state: present
    create: yes
  become: yes

- name: Vérification que le service SSH est actif et démarré
  ansible.builtin.service:
    name: ssh
    state: started
    enabled: true

- name: Création du groupe TOPGUN
  ansible.builtin.group:
    name: TOPGUN
  become: yes

- name: Création d'utilisateurs
  ansible.builtin.user:
    name: "{{ item.name }}"
    group: TOPGUN
    shell: /bin/bash
    create_home: yes
    password: "{{ item.password | default(omit) }}"
    state: present
  loop:
    - { name: 'maverik', password: '*' }
    - { name: 'charlie' }
    - { name: 'goose' }
  become: yes

- name: Mise en place de sudoers pour maverik
  ansible.builtin.copy:
    dest: /etc/sudoers.d/maverik
    content: 'maverik ALL=(ALL) NOPASSWD: /sbin/reboot, /usr/bin/apt update, /usr/bin/apt upgrade'
    mode: '0440'
  notify: Restart SSH
  become: yes

- name: Mise en place de sudoers pour charlie
  ansible.builtin.copy:
    dest: /etc/sudoers.d/charlie
    content: |
      Defaults:charlie timestamp_timeout=15
      charlie ALL=(ALL) ALL
    mode: '0440'
  notify: Restart SSH
  become: yes

- name: Restriction des accès SSH à l'utilisateur goose
  ansible.builtin.user:
    name: goose
    shell: /usr/sbin/nologin
  become: yes

- name: Déployer la clé publique SSH de charlie
  ansible.builtin.authorized_key:
    user: charlie
    key: "{{ lookup('file', 'files/charlie_key.pub') }}"
    state: present
  become: yes
