---
# Configuration OpenLDAP
openldap_listen_ip: "127.0.0.1"
openldap_port: 389

# Configuration AD DC01
ad_server: "192.168.2.2"
ad_port: 636

# Configuration OpenLDAP locale
openldap_base_dn: "{{ ad_base_dn }}"
openldap_bind_dn: "{{ vault_ldap_proxy_bind_dn }}"
openldap_bind_mail: "{{ vault_ldap_proxy_bind_mail }}"
openldap_bind_password: "{{ vault_ldap_proxy_password }}"


ssl_cert: "/etc/ssl/certs/ca-certificates.crt"
