---
# Variables pour Roundcube
roundcube_default_host: "localhost"

roundcube_db_dsnw: "mysql://{{ roundcube_mysql_user }}:{{ roundcube_mysql_password }}@localhost/{{ roundcube_mysql_db }}"
roundcube_mysql_db: "{{ vault_roundcube_mysql_db }}"
roundcube_mysql_user: "{{ vault_roundcube_mysql_user }}"
roundcube_mysql_password: "{{ vault_roundcube_mysql_password }}"

roundcube_smtp_server: "127.0.0.1"
roundcube_smtp_port: 25


roundcube_repo: https://github.com/roundcube/roundcubemail
roundcube_version: 1.6.11

roundcube_user: www-data # roundcube
roundcube_group: www-data

roundcube_user_shell: /bin/false
roundcube_user_home: "/var/www"
roundcube_working_dir: "{{ roundcube_user_home }}"
roundcube_path: "{{ roundcube_working_dir }}/mail"


roundcube_des_key: ""

roundcube_dependencies:
  - php-intl
  - libmcrypt-dev
  - php-mysql
  - php-curl  # rcmcarddav
  - python3-mysqldb
  - git

roundcube_enable_installer: false