---
apache_conf_dir: "/etc/apache2/conf-available"

# System Settings
php_modules: ['php-curl', 'php-gd', 'php-mbstring', 'php-xml', 'php-xmlrpc', 'php-soap', 'php-intl', 'php-zip']

# mod_security
sec_audit_log: "/var/log/apache2/modsec_audit.log"  # Chemin corrigé
sec_audit_log_parts: "ABIFHZ"                       # Headers + Body
sec_server_signature: "Apache"
sec_rule_remove_by_id: "960017,970901,960015"

# Info WordPress
wordpress_version: "6.4.2"
wordpress_url: "https://wordpress.org/wordpress-{{ wordpress_version }}.tar.gz"
wordpress_root: "/var/www/wordpress"

http_host: "blog.epitaf.local"
https_host: "192.168.3.2"
http_root: "/var/www/html"
https_root: "/var/www/html"
http_conf: "http-vhost.conf"
https_conf: "https-vhost.conf"
http_port: "8000"
https_port: "10000"

# MySQL Settings
mysql_root_password: "root_password"
mysql_db: "wordpress"
mysql_user: "infra_01"
mysql_password: "password"

# TLS
ssl_cert: "/etc/ssl/certs/fullchain-nginx.pem"
ssl_key: "/etc/ssl/private/nginx.key"

# Kerberos
kerberos_conf: "krb5.conf"
kerberos_realm: "EPITAF.LOCAL"
kerberos_domain: "epitaf.local"
kerberos_dc: "dc01.epitaf.local"
kerberos_service_name: "HTTP/infra_01.epitaf.local@EPITAF.LOCAl"    # Verifier le fqdn(le nom du domaine) : HTTP/<fqdn>@<REALM>
kerberos_keytab: "/etc/apache2/http.keytab"                         # Le fichier contenant les identifiants chiffrés du service.

# MATOMO
matomo_root: "/var/www/matomo"
