---
apache_conf_dir: "/etc/apache2/conf-available"

# mod_security
sec_audit_log: "/var/log/apache2/modsec_audit.log"  # Chemin corrigé
sec_audit_log_parts: "ABIFHZ"                       # Headers + Body
sec_server_signature: "Apache"
sec_rule_remove_by_id: "960017,970901,960015"

# Info WordPress
http_host: "blog.epitaf.local"
https_host: "secure.epitaf.local"
http_root: "/var/www/html"
https_root: "/var/www/secure"

# TLS
# ssl_cert: "/etc/letsencrypt/live/example.com/fullchain.pem"
# ssl_key: "/etc/letsencrypt/live/example.com/privkey.pem"
