---
- name: Installer les paquets de nginx 
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  become: true
  loop:
    - nginx
    - nginx-extras

- name: Copier la configuration globale de nginx
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  become: true

- name: Copier la configuration du serveur web
  template:
    src: default.conf.j2
    dest: /etc/nginx/sites-available/default
  become: true

- name: Copier les certificats SSL
  copy:
    src: ssl/
    dest: /etc/nginx/ssl/
  become: true