---
- name: Installer les paquets nécéssaires
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  become: true
  loop:
    - nginx
    - nginx-extras

- name: Copier la page 404
  ansible.builtin.copy:
    src: sites/404.html
    dest: /var/www/html/404.html
    mode: '0644'
  become: true

- name: Copier le site web static 'top gun'
  ansible.builtin.copy:
    src: sites/topgun/
    dest: /var/www/html/
    mode: '0644'
  become: true
  notify: Restart nginx

- name: Copier la configuration globale
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: '0644'
  become: true
  notify: Restart nginx

- name: Copier la configuration du serveur web
  ansible.builtin.template:
    src: default.conf.j2
    dest: /etc/nginx/sites-available/default
    mode: '0644'
  become: true
  notify: Restart nginx

- name: Copier les certificats SSL
  ansible.builtin.copy:
    src: ssl/
    dest: /etc/nginx/ssl/
    mode: '0644'
  become: true
  notify: Restart nginx
