- name: Load and execute every role
  hosts: webservers
  tasks:
    - name: Load and execute NGINX role
      ansible.builtin.include_role:
        name: roles/nginx
    - name: Load and execute SSH role
      ansible.builtin.include_role:
        name: roles/ssh
