- name: Load and execute every role
  hosts: webservers
  tasks:
    - name: Load and execute NGINX role
      ansible.builtin.include_role:
        name: nginx
    - name: Load and execute FAIL2BAN role
      ansible.builtin.include_role:
        name: fail2ban
